DROP DATABASE IF EXISTS `db1`;

CREATE DATABASE `db1`;

USE `db1`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `user_id` INT (11) NOT NULL AUTO_INCREMENT,
  `name` TEXT,
  `email` TEXT NOT NULL,
  `password` TEXT,
  `create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON
UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
);

CREATE TABLE `mail_auth` (
  `auth_id` INT AUTO_INCREMENT,
  `email` TEXT NOT NULL,
  `number` TEXT NOT NULL,
  `is_authenticated` BOOLEAN DEFAULT false,
  `create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`auth_id`)
);